ger={
    "Autos":"Autos",
    "Hagel":"Hagel",
    "Motorhaube":"Motorhaube",
    "Dach":"Dach",
    "A Säule links":"A Säule links",
    "A Säule rechts":"A Säule rechts",
    "Tür vorne links":"Tür vorne links", 
    "Tür vorne rechts":"Tür vorne rechts", 
    "Tür hinten links":"Tür hinten links", 
    "Tür hinten rechts":"Tür hinten rechts", 
    "Kotflügel vorne links":"Kotflügel vorne links", 
    "Kotflügel vorne rechts":"Kotflügel vorne rechts", 
    "Kotflügel hinten links":"Kotflügel hinten links", 
    "Kotflügel hinten rechts":"Kotflügel hinten rechts", 
    "Heckklappe oben":"Heckklappe oben",
    "Heckklappe unten":"Heckklappe unten", 
    "Name / VIN":"Name / VIN",
    "10 AW":"10 AW",
    "12 AW":"12 AW",
    "Fertig":"Fertig",
    "Abbrechen":"Abbrechen",
    "Möchtest du das Auto wirklich löschen? ":"Möchtest du das Auto wirklich löschen? ",
    "Ja":"Ja",
    "Nein":"Nein",
    "Beispielauto":"Beispielauto",
    "Alu":"Alu",
    "Kleben":"Kleben",
    "Drücken":"Drücken",
    "Suche":"Suche",
    "Teil":"Teil",
    "mm":"mm",
    "Anzahl":"Anzahl",
    "Extra":"Extra",
    "AW":"AW",
    "Rüstzeit":"Rüstzeit",
    "Finish":"Finish",
}

rus={
    "Autos":"Aвто",
    "Hagel":"Град",
    "Motorhaube": "Капот",
    "Dach": "Крыша",
    "A Säule links": "Стойка A слева",
    "A Säule rechts": "Стойка A справа",
    "Tür vorne links": "Передняя левая дверь",
    "Tür vorne rechts": "Передняя правая дверь",
    "Tür hinten links": "Задняя левая дверь",
    "Tür hinten rechts": "Задняя правая дверь",
    "Kotflügel vorne links": "Переднее левое крыло",
    "Kotflügel vorne rechts": "Переднее правое крыло",
    "Kotflügel hinten links": "Заднее левое крыло",
    "Kotflügel hinten rechts": "Заднее правое крыло",
    "Heckklappe oben": "Крышка багажника сверху",
    "Heckklappe unten": "Крышка багажника снизу",
    "Name / VIN": "Имя / VIN",
    "10 AW": "10 AW",
    "12 AW": "12 AW",
    "Fertig": "Готово",
    "Abbrechen": "Отмена",
    "Möchtest du das Auto wirklich löschen? ": "Вы действительно хотите удалить автомобиль? ",
    "Ja": "Да",
    "Nein": "Нет",
    "Beispielauto": "Пример автомобиля",
    "Alu": "Алюминий",
    "Kleben": "Клеить",
    "Drücken": "Нажимать",
    "Suche": "Поиск",
    "Teil": "Часть",
    "mm": "мм",
    "Anzahl": "Количество",
    "Extra": "Дополнительно",
    "AW": "AW",
    "Rüstzeit":"время на наладку",
    "Finish":"финиш",
}

rum={
    "Autos":"Mașină",
    "Hagel":"Grindină",
    "Motorhaube": "Capotă",
    "Dach": "Acoperiș",
    "A Säule links": "Stâlp A stânga",
    "A Säule rechts": "Stâlp A dreapta",
    "Tür vorne links": "Ușa din față stânga",
    "Tür vorne rechts": "Ușa din față dreapta",
    "Tür hinten links": "Ușa din spate stânga",
    "Tür hinten rechts": "Ușa din spate dreapta",
    "Kotflügel vorne links": "Aripa din față stânga",
    "Kotflügel vorne rechts": "Aripa din față dreapta",
    "Kotflügel hinten links": "Aripa din spate stânga",
    "Kotflügel hinten rechts": "Aripa din spate dreapta",
    "Heckklappe oben": "Capacul portbagajului sus",
    "Heckklappe unten": "Capacul portbagajului jos",
    "Name / VIN": "Nume / VIN",
    "10 AW": "10 AW",
    "12 AW": "12 AW",
    "Fertig": "Finalizat",
    "Abbrechen": "Anulare",
    "Möchtest du das Auto wirklich löschen? ": "Vrei cu adevărat să ștergi mașina?",
    "Ja": "Da",
    "Nein": "Nu",
    "Beispielauto": "Mașină exemplu",
    "Alu": "Al",
    "Kleben": "Lipiți",
    "Drücken": "Apasă",
    "Suche": "Caută",
    "Teil": "Parte",
    "mm": "mm",
    "Anzahl": "Număr",
    "Extra": "Extra",
    "AW": "AW",
    "Rüstzeit":"Timp de configurare",
    "Finish":"Termina",
}